apiVersion: v1  # API version used for the service definition
kind: Service  # Type of Kubernetes object, in this case, a Service
metadata:  # Metadata for the service
  annotations:  # Annotations for additional information
    kompose.cmd: kompose convert  # Command used to generate this file with Kompose
    kompose.version: 1.32.0 (765fde254)  # Version of Kompose used
  labels:  # Labels for the service
    io.kompose.service: db  # Label to identify the service
  name: db  # Name of the service
spec:  # Specification of the service
  ports:  # Ports exposed by the service
    - name: "5432"  # Name of the port
      port: 5432  # Port number exposed by the service
      targetPort: 5432  # Port number the service targets on the container
  selector:  # Selector to identify the pods that the service applies to
    io.kompose.service: db  # Selector label to match the pods
