version: "3.8"  # Specify the version of the Docker Compose file format

services:  # Define the services that make up the application

  frontend:  # Service definition for the frontend
    image: "doc-react:v1.11"  # Specify the image to use for the frontend
    build:  # Build configuration for the frontend
      context: ./webapp  # Context for building the image, pointing to the ./webapp directory
    container_name: 'react-demo-container'  # Name the container for easy identification
    ports:  # Map the host port to the container port
      - 3000:3000  # Expose port 3000 on the host to port 3000 in the container

  db:  # Service definition for the database
    image: "postgres:14.1-alpine"  # Specify the image to use for PostgreSQL
    container_name: "doc-pgsql-container"  # Name the container for easy identification
    ports:  # Map the host port to the container port
      - 5432:5432  # Expose port 5432 on the host to port 5432 in the container
    volumes:  # Define volumes for persistent storage
      - db:/var/lib/postgresql/data  # Mount the db volume to the PostgreSQL data directory
    environment:  # Set environment variables for PostgreSQL
      POSTGRES_DB: doc-db  # Database name
      POSTGRES_USER: postgres  # Database user
      POSTGRES_PASSWORD: postgres  # Database password

  backend:  # Service definition for the backend
    image: 'devops-demo:v404'  # Specify the image to use for the backend
    build:  # Build configuration for the backend
      context: ./  # Context for building the image, pointing to the current directory
    container_name: 'devops-demo-container'  # Name the container for easy identification
    ports:  # Map the host port to the container port
      - 8080:8080  # Expose port 8080 on the host to port 8080 in the container
    depends_on:  # Define service dependencies
      - db  # The backend service depends on the db service
    environment:  # Set environment variables for the backend
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/doc-db  # JDBC URL for the database connection
      - SPRING_DATASOURCE_USERNAME=postgres  # Database user
      - SPRING_DATASOURCE_PASSWORD=postgres  # Database password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # Hibernate DDL auto setting

volumes:  # Define named volumes for persistent storage
  db:  # Define the db volume
    driver: local  # Use the local driver for the volume
