apiVersion: v1  # API version used for the Service
kind: Service  # Type of Kubernetes object, in this case, a Service
metadata:  # Metadata for the Service
  annotations:  # Annotations for additional information
    kompose.cmd: kompose convert  # Command used to generate this file with Kompose
    kompose.version: 1.32.0 (765fde254)  # Version of Kompose used
  labels:  # Labels for the Service
    io.kompose.service: frontend  # Label to identify the service
  name: frontend  # Name of the Service
spec:  # Specification of the Service
  ports:  # Ports exposed by the Service
    - name: "3000"  # Name of the port
      port: 3000  # Port number exposed by the Service
      targetPort: 3000  # Port number the Service targets on the container
  selector:  # Selector to identify the pods that the Service applies to
    io.kompose.service: frontend  # Selector label to match the pods
