apiVersion: apps/v1  # API version used for the Deployment
kind: Deployment  # Type of Kubernetes object, in this case, a Deployment
metadata:  # Metadata for the Deployment
  annotations:  # Annotations for additional information
    kompose.cmd: kompose convert  # Command used to generate this file with Kompose
    kompose.version: 1.32.0 (765fde254)  # Version of Kompose used
  labels:  # Labels for the Deployment
    io.kompose.service: frontend  # Label to identify the service
  name: frontend  # Name of the Deployment
spec:  # Specification of the Deployment
  replicas: 1  # Number of pod replicas
  selector:  # Selector to match pods managed by this Deployment
    matchLabels:  # Labels for the selector
      io.kompose.service: frontend  # Label to match the pods
  template:  # Template for the pod
    metadata:  # Metadata for the pod
      annotations:  # Annotations for additional information
        kompose.cmd: kompose convert  # Command used to generate this file with Kompose
        kompose.version: 1.32.0 (765fde254)  # Version of Kompose used
      labels:  # Labels for the pod
        io.kompose.network/devops-demo-default: "true"  # Network label
        io.kompose.service: frontend  # Label to identify the service
    spec:  # Specification of the pod
      containers:  # List of containers in the pod
        - image: doc-react:v1.11  # Docker image for the container
          imagePullPolicy: Never  # Image pull policy for the container
          name: react-demo-container  # Name of the container
          ports:  # Ports exposed by the container
            - containerPort: 3000  # Port number inside the container
              hostPort: 3000  # Port number on the host
              protocol: TCP  # Protocol used for the port
      restartPolicy: Always  # Restart policy for the pod
