name: CI

on:
  workflow_dispatch:
  push:
    branches: [ Ci ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Start PostgreSQL
        uses: docker://postgres:14.1
        with:
          env:
            POSTGRES_DB: doc-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          timeout-minutes: 2
      - name: Run Tests
        run: | 
          sleep 10
          mvn -B test

  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - run: mkdir staging && cp target/*.jar staging
