name: CI

on:
  workflow_dispatch:
  push:
    branches: [ Ci ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Start PostgreSQL
        run: |
          docker run --name postgres_container -d -e POSTGRES_DB=doc-db -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:14.1
          sleep 30  # Wait for PostgreSQL container to start

      - name: Run Tests
        run: | 
          mvn -B test

  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - run: mkdir staging && cp target/*.jar staging
